### ISSUE TITLE
🔴 Unable to hear disconnect/error event on bridges when breaking connection

### ISSUE THREAD

**Issue by eynort** [beyondjs/backend#1]
# 🐛 Context:

I am doing the integration of an app where there is a process where it is necessary to obtain information, obviously along the way there may be a problem of disconnection by the user and I would like to be able to listen when the connection with the bridges is down to act based on that.

## Issue:

I am currently unable to detect when the disconnect/error event occurs, they only appear in the console, no catch is being able to treat it.

![image](https://github.com/beyondjs/backend/assets/90587911/8b27cbff-5d4a-4050-84d4-d6a61ac97c65)

## Use case:
Generate a somewhat similar use case on the following 
*repository*: https://github.com/jircdev/beynd-backend-cases/tree/disconnection 
*branch*: `disconnection`.
Proyect: url: http://localhost:6510/

To execute the error you have to click the execute button that will appear in the middle of the screen and go to the `network` tab of the dev-tools and select the `disconnected` option, as we can see none of the catch is executed (when there is an error in the process always shows an error message on the screen, however, at the time of making the disconnection does not happen).

![image](https://github.com/beyondjs/backend/assets/90587911/5f9a51ad-70e8-4200-987b-2f290ddda405)

## Code:
The code is divided into two essential parts:

- Entities: (representing the central entity `users` and its respective bridge), can be found in: 
`bridges-conexion\modules\entities\module.json`.

And the

- View code: (Represents the view code and its respective store that does the treatment to show the error in the view), you can find it in: 

`bridges-conexion\modules\home\module.json`.

## Review:
Let's review the code:

In the bridge (there is only one and it is in `bridges-conexion\modules\entities\bridge` a simulation is made to a common call to a backend to make a get of users.

![image](https://github.com/beyondjs/backend/assets/90587911/47100447-9aaa-42f4-b5f9-8bdf71dbc0f3)

It only returns the array of users.

In the single entity `users` we only have the call to the bridge method and the only thing that is done is to treat the response to handle the standard responses and its ubicated in: `bridges-conexion\modules\entities\ts\index.ts`.

![image](https://github.com/beyondjs/backend/assets/90587911/acc116b1-a2ca-4a95-ba04-aa4a58d2fe26)

And finally we have the store of our view that the only thing it does is to use the api of the entity `users` to obtain its answer and to process it its ubicated in: `bridges-conexion\modules\home\ts\store.ts`.

![image](https://github.com/beyondjs/backend/assets/90587911/1d4597e2-0655-45db-968d-6afc9409aea2)

**Comment by ftovar8** [comment]
Thank you for reporting this issue. We appreciate your feedback.

We wanted to inform you that this issue has been addressed and resolved in the latest version (0.1.7) of the library.

If you encounter any further issues or have any additional questions, please don't hesitate to let us know. We're here to assist you.

You can find the latest release, version 0.1.7, here: [Link to the latest release](https://www.npmjs.com/package/@beyond-js/backend)

Best regards,
Felix Tovar
